### ISSUE TITLE
Spline wavelet

### ISSUE THREAD

**Issue by MohammadFakhreddin** [matteotiziano/simple-wavelet#1]
Hello, 
Thank you very much for this awesome library. I'm new to wavelet, so I apologize for my question.
I tested the Haar wavelet example, and everything works fine. What are the input parameters for the wavelet class for a spline wavelet? How can I find them?

**Comment by matteotiziano** [comment]
Hello!

This library is based on a [`Wavelet`](https://github.com/matteotiziano/simple-wavelet/blob/64abe8d60f9f49fc3c9e707a688589869d3e1369/wavelet.h#L67-L68) object which can implement any wavelet transform by passing the appropriate decomposition and reconstruction filters (i.e., 1d arrays) in the constructor as 
```C++
const Wavelet<double> haar(Lo_D, Hi_D, Lo_R, Hi_R);
```

The example in `main.cpp` shows how to build a Haar `Wavelet` transform from its filters
https://github.com/matteotiziano/simple-wavelet/blob/64abe8d60f9f49fc3c9e707a688589869d3e1369/main.cpp#L30-L36

To implement a transform using a spline wavelet, you can update the coefficients to those of a spline wavelet. There are several types of spline wavelets, so I will make an assumption and use Biorthogonal wavelets which can be considered a specific example of B-spline wavelets. In particular I am using bior2.2 which is often used in wavelet-based image processing and is indeed based on B-spline functions.  I found the coefficients [here](https://wavelets.pybytes.com/wavelet/bior2.2/).

So the code in `main.cpp` becomes

```C++
  // Filters definition of bior2.2 transform
  const double sqrt2 = std::sqrt(2.0);
  const std::vector<double> Lo_D = { 
      0.0,
      -0.125 * sqrt2,
      0.250 * sqrt2,
      0.750 * sqrt2,
      0.250 * sqrt2,
      -0.125 * sqrt2,
  };

  const std::vector<double> Hi_D = { 
      0.0,
      0.250 * sqrt2,
      -0.5 * sqrt2,
      0.250 * sqrt2,
      0.0,
      0.0,
  };

  const std::vector<double> Lo_R = { 
      0.0,
      0.250 * sqrt2,
      0.5 * sqrt2,
      0.250 * sqrt2,
      0.0,
      0.0,
  };

  const std::vector<double> Hi_R = { 
      0.0,
      0.125 * sqrt2,
      0.250 * sqrt2,
      -0.750 * sqrt2,
      0.250 * sqrt2,
      0.125 * sqrt2,
  };
  // Instantiate a bior2.2 object with Haar filters
  const Wavelet<double> bior22(Lo_D, Hi_D, Lo_R, Hi_R);
```

**Comment by MohammadFakhreddin** [comment]
@matteotiziano Thanks a lot! I figured it out 2 years ago but appreciate the answer  :) It should be helpful for anyone who needs this repo.

**Comment by matteotiziano** [comment]
Yep, really sorry for the very late reply :D
